At-Gerenciamento de Eletrodomésticos/Models/Eletrodomestico.cs
namespace At_Gerenciamento_de_Eletrodomésticos.Models
{
    public abstract class Eletrodomestico
    {
        public string Marca { get; set; }

        public string Modelo { get; set; }

        public double ConsumoEnergetico{ get; set; }
       

        public abstract string ExibirDetalhes();
    }
}

At-Gerenciamento de Eletrodomésticos/Models/ErrorViewModel.cs
namespace At_Gerenciamento_de_Eletrodomésticos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

At-Gerenciamento de Eletrodomésticos/Models/Geladeira.cs
namespace At_Gerenciamento_de_Eletrodomésticos.Models
{
    public class Geladeira : Eletrodomestico
    {
        public int CapacidadeLitros { get; set; }

        public bool TemFreezer { get; set; }

        public override string ExibirDetalhes()
        {
            return $"Marca: {Marca}, Modelo: {Modelo}, Consumo: {ConsumoEnergetico}, Freezer {(TemFreezer ? "Sim" : "Não")}";

        }
    }
}

At-Gerenciamento de Eletrodomésticos/Models/Televisor.cs
namespace At_Gerenciamento_de_Eletrodomésticos.Models
{
    public class Televisor : Eletrodomestico
    {
        public int TamanhoTela { get; set; }

        public bool EhSmart { get; set; }

        public override string ExibirDetalhes()
        {
            return $"Marca: {Marca}, Modelo: {Modelo}, Tela: {TamanhoTela}, EhSmart: {(EhSmart? "Sim" : "Não")}";

        }
    }
}

At-Gerenciamento de Eletrodomésticos/Controllers/EletrodomesticoController.cs
using At_Gerenciamento_de_Eletrodomésticos.Models;
using Microsoft.AspNetCore.Mvc;

namespace At_Gerenciamento_de_Eletrodomésticos.Controllers
{
    public class EletrodomesticoController : Controller
    {
        public IActionResult Index()
        {

            List<Eletrodomestico> eletrodomesticos = new List<Eletrodomestico>
            {
                new Geladeira{ Marca = "Electrolux", Modelo = "IF45S 127V", ConsumoEnergetico = 42, CapacidadeLitros = 410, TemFreezer = true},
                new Geladeira{ Marca = "Philco", Modelo = "Duplex", ConsumoEnergetico = 2022, CapacidadeLitros = 413, TemFreezer = true },
                new Televisor{ Marca = "LG", Modelo = "50UR871C0SA", ConsumoEnergetico = 2022, EhSmart = true, TamanhoTela = 50 }

            };
            return View(eletrodomesticos);
        }
    }
}

At-Gerenciamento de Eletrodomésticos/Controllers/HomeController.cs
using At_Gerenciamento_de_Eletrodomésticos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace At_Gerenciamento_de_Eletrodomésticos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

At-Gerenciamento de Eletrodomésticos/Views/Eletrodomestico/Index.cshtml
@model List<Eletrodomestico>

<h1>Lista de Eletrodomestico </h1>

<table class=" table table-striped table-bordered">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Consumo Energetico(kWh)</th>
            <th>Detalhes</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var eledomesticos in Model)
        {
            <tr>
                <td>@eledomesticos.Marca</td>
                <td>@eledomesticos.Modelo</td>
                <td>@eledomesticos.ConsumoEnergetico</td>
                <td>
                    @if (eledomesticos is Geladeira)
                    {
                        <strong>Freezer:</strong>@(((Geladeira)eledomesticos).TemFreezer ? "Sim" : "Não")<br />
                        <strong>Tamanho(L):</strong>@(((Geladeira)eledomesticos).CapacidadeLitros)<br />
                    }
                    else if (eledomesticos is Televisor)
                    {
                        <strong>Tamanho da Tela:</strong>@(((Televisor)eledomesticos).TamanhoTela)<br />
                        <strong>EhSmart:</strong>@(((Televisor)eledomesticos).EhSmart ? "Sim" : "Não")<br />
                       
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

At-Gerenciamento de Eletrodomésticos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

At-Gerenciamento de Eletrodomésticos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - At_Gerenciamento_de_Eletrodomésticos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/At_Gerenciamento_de_Eletrodomésticos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">At_Gerenciamento_de_Eletrodomésticos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eletrodomestico" asp-action="Index">Eletrodomesticos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - At_Gerenciamento_de_Eletrodomésticos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>